server:
  contextPath: /api/v1
#  port: 8080

spring:
  profiles:
    active: develop
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tokyo

logging:
  file: logs/app.log
  level:
    root: INFO

swasd:
  sample: test_with_override
  api_version: 1.0.0
  api_no_version_check: true
